<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $query
 */

$translate = $this->plugin('translate');
$resourceClassSelect = $this->plugin('resourceClassSelect');
$siteSetting = $this->plugin('siteSetting');

$isSiteRequest = version_compare(\Omeka\Module::VERSION, '1.3.0', '<') ? $this->params()->fromRoute('__SITE__') : $this->status()->isSiteRequest();
$usedTerms = $isSiteRequest ? $siteSetting('next_search_used_terms') : false;

// Prepare the resource class query.
$ids = isset($query['resource_class_id']) ? $query['resource_class_id'] : [];
if (!is_array($ids)) {
    $ids = [$ids];
}
$ids = array_filter($ids);
if (!$ids) {
    $ids = [null];
}
?>
<div id="resource-class" class="field removable multi-value" role="group">
    <div class="field-meta">
        <span id="by-resource-class-label" class="label"><?php echo $translate('Search by class'); ?></span>
        <?php echo $this->hyperlink('', '#', ['class' => 'expand', 'title' => $translate('Expand')]); ?>
        <div class="collapsible">
            <div class="field-description"><?php echo $translate('Searches for items that are any of these classes.'); ?></div>
        </div>
    </div>
    <div class="inputs">
        <?php foreach ($ids as $id): ?>
        <div class="value">
            <?php echo $resourceClassSelect([
                'name' => 'resource_class_id[]',
                'attributes' => [
                    'value' => $id,
                    'aria-labelledby' => 'by-resource-class-label',
                ],
                'options' => [
                    'used_terms' => $usedTerms,
                ],
            ]); ?>
            <button type="button" class="o-icon-delete remove-value button"><?php echo $translate('Remove value'); ?></button>
        </div>
        <?php endforeach; ?>
        <a href="#" class="add-value button"><?php echo $translate('Add new class'); ?></a>
    </div>
</div>
