<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var Laminas\Navigation\Navigation $breadcrumbs
 * @var array $options Options provided to the helper, merged with default values.
 * @var array $crumbs Flat list of crumb, that is an array with "label", "uri", "resource", if any.
 * @deprecated $crumbs is kept for old themes, not in this partial (see old releases).
 */

// Quick hack to insert a span if it is the current page (simpler to theme, and simpler than creating a specific partial).
$separator = ' ' . $options['separator'] . " \n";
$html = $this->navigation()->breadcrumbs($breadcrumbs)->setSeparator($separator);
if ($options['current'] && $lastLinkPos = mb_strrpos($html, '</a>' . $separator)):
    $html = mb_substr($html, 0, $lastLinkPos + 4 + mb_strlen($separator)) . '<span class="active">' . mb_substr($html, $lastLinkPos + 4 + mb_strlen($separator)) . '</span>';
endif;
?>

<nav id="breadcrumb" class="breadcrumbs">
    <?= $html ?>
</nav>
