<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $crumbs Each crumb is an array with "url", "title", and "resource" if any.
 * @var array $options The options provided to the helper, merged with default values.
 */

$hyperlink = $this->plugin('hyperlink');
?>

<nav id="breadcrumb" class="breadcrumb">
<?php
// Remove the last crumb, that should not be a link.
if ($options['current']):
    $last = array_pop($crumbs);
endif;

foreach ($crumbs as $crumb):
    echo $hyperlink($crumb['title'], $crumb['url']);
    echo " &gt; \n";
endforeach;
?>
<?php if ($options['current']): ?>
    <span class="active"><?= $last['title'] ?></span>
<?php endif; ?>
</nav>
