<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\MediaRepresentation $media
 * @var \Omeka\Api\Representation\MediaRepresentation $resource
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
    <div class="meta-group">
        <h4><?php echo $translate('Renderer'); ?></h4>
        <div class="value"><?php echo $escape($translate($media->renderer())); ?></div>
    </div>
